apiVersion: v1
items:
- apiVersion: v1
  kind: ClusterRole
  metadata:
    name: enmasse-namespace-admin
  rules:
  - apiGroups:
    - authentication.k8s.io
    resources:
    - tokenreviews
    verbs:
    - create
  - apiGroups:
    - ''
    - rbac.authorization.k8s.io
    resources:
    - rolebindings
    - roles
    verbs:
    - create
  - apiGroups:
    - ''
    - authorization.openshift.io
    resources:
    - namespaces
    - rolebindings
    verbs:
    - get
    - list
    - create
    - delete
    - update
    - patch
  - apiGroups:
    - authorization.k8s.io
    resources:
    - localsubjectaccessreviews
    verbs:
    - create
- apiVersion: v1
  kind: ClusterRole
  metadata:
    name: enmasse-infra-admin
  rules:
  - apiGroups:
    - ''
    - extensions
    - rbac.authorization.k8s.io
    - authorization.k8s.io
    - authentication.k8s.io
    resources:
    - ResourceAll
    verbs:
    - create
    - delete
    - list
    - get
    - watch
    - update
    - patch
- apiVersion: v1
  kind: ClusterRole
  metadata:
    name: enmasse-addressspace-admin
  rules:
  - resources:
    - configmaps
    verbs:
    - get
    - list
    - watch
    - create
    - update
    - patch
    - delete
- apiVersion: v1
  kind: ClusterRole
  metadata:
    name: enmasse-address-admin
  rules:
  - apiGroups:
    - ''
    resources:
    - configmaps
    verbs:
    - create
    - delete
    - list
    - get
    - watch
    - update
    - patch
kind: List
